import 'package:komodo_coin_updates/src/persistence/persistence_provider.dart';

abstract class PersistedBasicType<T> implements ObjectWithPrimaryKey<T> {
  PersistedBasicType(this.primaryKey, this.value);

  final T value;

  @override
  final T primaryKey;
}

class PersistedString extends PersistedBasicType<String> {
  PersistedString(super.primaryKey, super.value);
}

// Adapter is now generated by Hive CE from `lib/hive/hive_adapters.dart`.
