name: dragon_logs
description: A Flutter-compatible logging package with support for Web Wasm. Provides flexible logging capabilities across all Flutter platforms.
version: 2.0.0

homepage: https://github.com/komodoplatform/komodo_defi_framework
repository: https://github.com/komodoplatform/komodo_defi_framework

environment:
  sdk: ^3.7.0
  # flutter: ">=3.29.0 <3.30.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  path_provider: ^2.1.0
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
