// (Internal/private) Generated by the `index_generator` package with the `index_generator.yaml` configuration file.

/// Internal/private classes related to CoinGecko market data provider functionality.
library _coingecko;

export 'data/coingecko_cex_provider.dart';
export 'data/coingecko_repository.dart';
export 'models/coin_historical_data/code_additions_deletions4_weeks.dart';
export 'models/coin_historical_data/coin_historical_data.dart';
export 'models/coin_historical_data/community_data.dart';
export 'models/coin_historical_data/current_price.dart';
export 'models/coin_historical_data/developer_data.dart';
export 'models/coin_historical_data/image.dart';
export 'models/coin_historical_data/localization.dart';
export 'models/coin_historical_data/market_cap.dart';
export 'models/coin_historical_data/market_data.dart';
export 'models/coin_historical_data/public_interest_stats.dart';
export 'models/coin_historical_data/total_volume.dart';
export 'models/coin_market_chart.dart';
export 'models/coin_market_data.dart';
export 'models/coingecko_api_plan.dart';
