name: komodo_defi_framework
repository: https://github.com/KomodoPlatform/komodo_defi_framework

packages:
  - packages/**
  - products/**

commands:
  bootstrap:
    hooks:
      post:
        - melos run indexes:generate
        - melos run runners:generate
        - melos run assets:generate

scripts:
  indexes:generate:
    run: dart run index_generator
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: index_generator

  runners:generate:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    packageFilters:
      dependsOn:
        - build_runner

  upgrade:major:
    run: flutter pub upgrade --major-versions
    exec:
      concurrency: 1
    # packageFilters:
    #   exclude:
    #     - packages/**
    #     - products/**

  assets:generate:
    run: flutter build bundle
    packageFilters:
      dependsOn:
        - komodo_defi_framework
