name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - playground
  - packages/komodo_coins
  - packages/komodo_defi_rpc_methods
  - packages/komodo_symbol_converter
  - packages/komodo_wallet_cli
  - packages/komodo_defi_framework
  # - packages/komodo_defi_framework/example
  - packages/komodo_defi_sdk
  - packages/komodo_defi_sdk/example
  - packages/komodo_ui
  - packages/komodo_ui/widgetbook
  - packages/komodo_defi_local_auth
  - packages/komodo_defi_types
  - packages/komodo_wallet_build_transformer

dependency_overrides:
  flutter_secure_storage_web:
     git:
      url: https://github.com/mogol/flutter_secure_storage.git
      ref: develop
      path: flutter_secure_storage_web