name: komodo_defi_framework
description: "A Flutter plugin for the Komodo DeFi Framework, supporting both
  native (FFI) and web (WASM) platforms."
version: 0.0.1
homepage: https://komodoplatform.com

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.2.2
  js: ^0.7.1
  logging: ^1.2.0
  path_provider: ^2.1.3
  plugin_platform_interface: ^2.0.2
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.11
  build_web_compilers: ^4.0.10
  ffigen: ^11.0.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      web:
        pluginClass: KomodoDefiFrameworkWeb
        fileName: web/kdf_plugin_web.dart

  # Uncomment this section if you have any assets to include
  # TODO: Conditionalize this so that web assets are only included for web builds
  # or ensure that web assets are not fetched in native builds
  assets:
    #   - assets/coins.json
    # TODO: Build transformer to copy all the assets instead of having to list all folders here
    - web/src/kdf/
    - web/src/kdflib_bootstrapper.js
    - web/src/kdf/snippets/
    - web/src/kdf/snippets/hw_common-c933ea30ea0fef0d/
    - web/src/kdf/snippets/libp2p-wasm-ext-7e5f5edb880ee0f5/
    - web/src/kdf/snippets/libp2p-wasm-ext-7e5f5edb880ee0f5/src/
    - web/src/kdf/snippets/web3-3a881fca17d19cd8/
  # Uncomment this section if you need to include any font assets
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700