name: dragon_charts_flutter
description: A lightweight and highly customizable charting library for Flutter.
version: 0.1.1-dev.1
homepage: https://komodoplatform.com
repository: https://github.com/KomodoPlatform/dragon_charts_flutter

environment:
  # sdk: '>=2.17.0 <4.0.0'
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
