analyzer:
  errors:
    public_member_api_docs: ignore
    
    # This is required to use Freezed in combination with 
    # `json_serializable`: https://github.com/rrousselGit/freezed
    invalid_annotation_target: ignore

include: package:very_good_analysis/analysis_options.6.0.0.yaml
