name: komodo_defi_rpc_methods
description: A package containing the RPC methods and responses for the Komodo
  DeFi Framework API
homepage: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter
version: 0.2.0+0
publish_to: "none"

environment:
  sdk: ^3.7.0

dependencies:
  collection: ^1.18.0
  decimal: ^3.0.2
  equatable: ^2.0.5
  freezed_annotation: ^3.0.0
  komodo_defi_types:
    path: ../komodo_defi_types

  meta: ^1.15.0
  path: any
dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^3.0.4
  index_generator: ^4.0.1
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^8.0.0
