name: komodo_defi_rpc_methods
description: A package containing the RPC methods and responses for the Komodo DeFi Framework API
homepage: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter
version: 0.1.0+1
publish_to: 'none'


environment:
  sdk: ^3.4.0

dependencies:
  komodo_defi_types:
    path: ../komodo_defi_types

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^6.0.0
