name: komodo_defi_rpc_methods
description: A package containing the RPC methods and responses for the Komodo DeFi Framework API
homepage: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter
version: 0.1.0+1


environment:
  sdk: ^3.4.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
