name: komodo_defi_rpc_methods
description: A package containing the RPC methods and responses for the Komodo DeFi Framework API
repository: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter
version: 0.3.0+1

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  collection: ^1.18.0
  decimal: ^3.2.1
  rational: ^2.2.3
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  komodo_defi_types: ^0.3.0+2
  meta: ^1.15.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^3.0.4
  index_generator: ^4.0.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^9.0.0
