// GENERATED CODE - DO NOT MODIFY BY HAND

// Copyright (c) 2025 Komodo Platform
// This is the main entry point for the Komodo UI Kit
//
// Do not manually edit. The indexes can be generated by running `flutter pub run index_generator`

/// Global constants and theme definitions
library komodo_ui.constants;

export 'package:flutter/material.dart' show Colors, TextTheme, ThemeData;
