// Generated by the `index_generator` package with the `index_generator.yaml` configuration file.

library _runtime_update_config;

export 'runtime_update_config.dart';
export 'runtime_update_config_repository.dart';
