name: widgetbook_workspace
description: "A demo catalog of the Komodo DeFi Framework's Flutter widgets."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0" 

dependencies:
  flutter:
    sdk: flutter
  komodo_ui:
    path: ../
  widgetbook: ^4.0.0-alpha.2
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  # build_runner: ^2.4.12
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^4.0.0-alpha.2

flutter:
  uses-material-design: true
