name: komodo_defi_local_auth
description: A package responsible for managing and abstracting out an
  authentication service on top of the API's methods
version: 0.3.0+1
repository: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0-beta.4
  freezed_annotation: ^3.0.0

  komodo_defi_framework: ^0.3.0+1
  komodo_defi_rpc_methods: ^0.3.0+1
  komodo_defi_types: ^0.3.0+2

  local_auth: ^2.3.0
  logging: ^1.3.0
  mutex: ^3.1.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  index_generator: ^4.0.1
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
