name: dragon_logs_example
description: An example app for dragon_logs package
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  dragon_logs:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
