import 'package:komodo_cex_market_data/src/binance/models/binance_exchange_info_reduced.dart';
import 'package:komodo_cex_market_data/src/binance/models/symbol_reduced.dart';

BinanceExchangeInfoResponseReduced buildComprehensiveExchangeInfo({
  int? serverTime,
}) {
  return BinanceExchangeInfoResponseReduced(
    timezone: 'UTC',
    serverTime: serverTime ?? DateTime.now().millisecondsSinceEpoch,
    symbols: [
      SymbolReduced(
        symbol: 'BTCUSDT',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'USDT',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCUSDC',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'USDC',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCBUSD',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'BUSD',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCEUR',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'EUR',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'ETHUSDT',
        status: 'TRADING',
        baseAsset: 'ETH',
        baseAssetPrecision: 8,
        quoteAsset: 'USDT',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'ETHUSDC',
        status: 'TRADING',
        baseAsset: 'ETH',
        baseAssetPrecision: 8,
        quoteAsset: 'USDC',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCTUSD',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'TUSD',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCDAI',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'DAI',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCUSDP',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'USDP',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCEURS',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'EURS',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCEURT',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'EURT',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCFRAX',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'FRAX',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCLUSD',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'LUSD',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCGUSD',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'GUSD',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCSUSD',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'SUSD',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
      SymbolReduced(
        symbol: 'BTCFEI',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'FEI',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
    ],
  );
}

BinanceExchangeInfoResponseReduced buildMinimalExchangeInfo({int? serverTime}) {
  return BinanceExchangeInfoResponseReduced(
    timezone: 'UTC',
    serverTime: serverTime ?? DateTime.now().millisecondsSinceEpoch,
    symbols: [
      SymbolReduced(
        symbol: 'BTCEUR',
        status: 'TRADING',
        baseAsset: 'BTC',
        baseAssetPrecision: 8,
        quoteAsset: 'EUR',
        quotePrecision: 8,
        quoteAssetPrecision: 8,
        isSpotTradingAllowed: true,
      ),
    ],
  );
}
