name: komodo_ccxt_bridge
description: CCXT-compatible API bridge (Shelf) for KDF via SDK
version: 0.0.1


environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  http: ^1.4.0
  komodo_defi_types:
    path: ../komodo_defi_types
  komodo_defi_rpc_methods:
    path: ../komodo_defi_rpc_methods

dev_dependencies:
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0

executables:
  komodo_ccxt_bridge:
