name: komodo_defi_framework
description: "A Flutter plugin for the Komodo DeFi Framework, supporting both
  native (FFI) and web (WASM) platforms."
version: 0.3.0+0
homepage: https://komodoplatform.com
publish_to: "none"

environment:
  sdk: '>=3.3.0 <4.0.0'
  # Minimum Flutter version is set quite high for build transformer capabilities.
  # If this is too high for your project, this can be lowered by commenting out
  # the following line and running the build transformer manually via CLI.
  flutter: '>=3.22.0'

dependencies:
  # aws_client: ^0.6.0
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.4.0
  komodo_coin_updates:
    path: ../komodo_coin_updates
  komodo_coins:
    path: ../komodo_coins
  komodo_defi_types:
    path: ../komodo_defi_types
  komodo_wallet_build_transformer:
    path: ../komodo_wallet_build_transformer
  logging: ^1.3.0
  mutex: ^3.1.0
  path: any
  path_provider: ^2.1.4
  plugin_platform_interface: ^2.0.2
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.14
  # build_web_compilers: ^4.0.10
  ffigen: ^19.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  js: any
  very_good_analysis: ^8.0.0
  yaml: ^3.1.2

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      web:
        pluginClass: KomodoDefiFrameworkWeb
        fileName: web/kdf_plugin_web.dart

  assets:
    - assets/config/
    - assets/coin_icons/png/
    - app_build/build_config.json
    
    - path: assets/.transformer_invoker
      transformers:
          - package: komodo_wallet_build_transformer
            args: [
            # Uncomment any of the following options to disable specific build
            # steps. They are executed in the order listed in `_build_steps`
            # in `packages/komodo_wallet_build_transformer/bin/komodo_wallet_build_transformer.dart`
              # Configure fetch_defi_api in `config/build_config.yaml`
              --fetch_defi_api,
              # Configure `fetch_coin_assets` in `config/build_config.yaml`
              --fetch_coin_assets,
              --copy_platform_assets,
              # Uncomment the following option to enable concurrent build step
              # execution. This is useful for reducing build time in development,
              # but is not recommended for production builds.
              # - --concurrent,

              # Uncomment the following option to enable verbose logging.
              # --log_level=finest,

              #! NB: There may be complications if we want to publish the
              # sub-packages as separate packages. However, Flutter's upcoming
              # support for native/web build hooks may simplify this process.
              # This package must be listed in the `package_config.json` of the
              # root Flutter app.
              --artifact_output_package=komodo_defi_framework,

              # The path to the build config file relative to the root of the
              # artifact output package.
              --config_output_path=app_build/build_config.json,

            ]
  # Uncomment this section if you need to include any font assets
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
