name: komodo_wallet_build_transformer
description: A build transformer for Komodo Wallet used for managing all build-time dependencies.
version: 0.4.0
repository: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

# Add regular dependencies here.
dependencies:
  args: ^2.6.0 # dart.dev
  crypto: ^3.0.3 # dart.dev
  html: ^0.15.4
  http: ^1.4.0 # dart.dev
  logging: ^1.3.0 # dart.dev
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.25.7
  very_good_analysis: ^9.0.0
