name: komodo_defi_remote
description: Tools for managing Komodo DeFi Framework instances on remote servers.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  args: ^2.6.0
  http: ^1.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  equatable: ^2.0.7


dev_dependencies:
  very_good_analysis: ^7.0.0
  test: ^1.24.0
