name: komodo_coin_updates
description: Runtime coin config update coin updates.
version: 1.0.0
publish_to: none # publishable packages can't have git dependencies

environment:
  sdk: ^3.8.1
  flutter: ">=3.35.0 <3.36.0"

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  http: ^1.4.0
  komodo_defi_types:
    path: ../komodo_defi_types
  very_good_analysis: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.25.7
