name: komodo_coin_updates
description: Runtime coin config update coin updates.
version: 1.0.0
publish_to: none # publishable packages can't have git dependencies

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0 <3.30.0"

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  hive: 2.2.3  
  hive_flutter: 1.1.0
  http: ^1.3.0 
  very_good_analysis: ^8.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
