name: komodo_coin_updates
description: Runtime coin config update coin updates.
version: 1.0.0
publish_to: none # publishable packages can't have git dependencies

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  http: 0.13.6 # dart.dev

  komodo_persistence_layer:
    path: ../komodo_persistence_layer/

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  flutter_bloc:
    git:
      url: https://github.com/KomodoPlatform/bloc.git
      path: packages/flutter_bloc/
      ref: 32d5002fb8b8a1e548fe8021d8468327680875ff # 8.1.1

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  equatable:
    git:
      url: https://github.com/KomodoPlatform/equatable.git
      ref: 2117551ff3054f8edb1a58f63ffe1832a8d25623 #2.0.5

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  hive:
    git:
      url: https://github.com/KomodoPlatform/hive.git
      path: hive/
      ref: 470473ffc1ba39f6c90f31ababe0ee63b76b69fe #2.2.3

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  hive_flutter:
    git:
      url: https://github.com/KomodoPlatform/hive.git
      path: hive_flutter/
      ref: 0cbaab793be77b19b4740bc85d7ea6461b9762b4 #1.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
