name: komodo_coin_updates
description: Runtime coin config update coin updates.
version: 1.0.0
publish_to: none # publishable packages can't have git dependencies

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0 <3.36.0"

# Add regular dependencies here.
dependencies:
  decimal: ^3.2.1
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  hive_ce: ^2.2.3+ce
  hive_ce_flutter: ^2.2.3+ce
  http: ^1.4.0
  json_annotation: ^4.9.0
  komodo_defi_types:
    path: ../komodo_defi_types
  very_good_analysis: ^8.0.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  hive_ce_generator: ^1.9.2
  hive_test: ^1.0.1
  json_serializable: ^6.7.1
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.7
