// (Internal/private) Generated by the `index_generator` package with the `index_generator.yaml` configuration file.

/// Internal/private classes related to common utilities for market data providers.
library _common;

export 'api_error_parser.dart';
