// Copyright (c) 2025 Komodo Platform
// This is the main entry point for the Komodo UI Kit
//
// DO NOT MANUALLY EDIT.
// The indexes can be generated by running `dart run index_generator`

/// Global constants and theme definitions
library komodo_ui.constants;

export 'package:flutter/material.dart' show Colors, TextTheme, ThemeData;
