name: komodo_cex_market_data
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none # publishable packages should not have git dependencies

environment:
  sdk: ">=3.7.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  decimal: ^3.2.1
  http: ^1.4.0 # dart.dev

  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  hive_ce: ^2.11.3 # Changed from `hive` to `hive_ce` (Community Edition) because `hive` is no longer maintained
  logging: ^1.3.0
  async: ^2.13.0 # same as transitive version in build_transformer package
  get_it: ^8.0.3
  komodo_defi_types:
    path: ../komodo_defi_types

dev_dependencies:
  flutter_lints: ^6.0.0 # flutter.dev
  mocktail: ^1.0.4
  test: ^1.25.7
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  build_runner: ^2.4.14
  very_good_analysis: ^8.0.0
