name: komodo_cex_market_data
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none # publishable packages should not have git dependencies

environment:
  sdk: ">=3.7.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  decimal: ^3.2.1
  http: ^1.4.0 # dart.dev

  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  komodo_defi_types:
    path: ../komodo_defi_types

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  hive: ^2.2.3 # Changed from git to pub.dev because git dependencies are not allowed in published packages

dev_dependencies:
  flutter_lints: ^6.0.0 # flutter.dev
  mocktail: ^1.0.4
  test: ^1.25.7
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  build_runner: ^2.4.14
