name: komodo_cex_market_data
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none # publishable packages should not have git dependencies

environment:
  sdk: ">=3.7.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  http: ^1.4.0 # dart.dev

  equatable: ^2.0.7

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106 (Outdated)
  hive_ce: ^2.11.3 # Changed from `hive` to `hive_ce` (Community Edition) because `hive` is no longer maintained

dev_dependencies:
  flutter_lints: ^6.0.0 # flutter.dev
  test: ^1.25.7
