name: komodo_cex_market_data
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none # publishable packages should not have git dependencies

environment:
  sdk: ">=3.6.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  http: 1.3.0 # dart.dev

  equatable: 2.0.7

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  hive: ^2.2.3 # Changed from git to pub.dev because git dependencies are not allowed in published packages

dev_dependencies:
  flutter_lints: ^5.0.0 # flutter.dev
  test: ^1.24.0
