// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:komodo_coin_updates/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AddressFormatAdapter());
    registerAdapter(CheckPointBlockAdapter());
    registerAdapter(CoinAdapter());
    registerAdapter(CoinConfigAdapter());
    registerAdapter(CoinInfoAdapter());
    registerAdapter(ConsensusParamsAdapter());
    registerAdapter(ContactAdapter());
    registerAdapter(ElectrumAdapter());
    registerAdapter(LinksAdapter());
    registerAdapter(NodeAdapter());
    registerAdapter(ProtocolAdapter());
    registerAdapter(ProtocolDataAdapter());
    registerAdapter(RpcUrlAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AddressFormatAdapter());
    registerAdapter(CheckPointBlockAdapter());
    registerAdapter(CoinAdapter());
    registerAdapter(CoinConfigAdapter());
    registerAdapter(CoinInfoAdapter());
    registerAdapter(ConsensusParamsAdapter());
    registerAdapter(ContactAdapter());
    registerAdapter(ElectrumAdapter());
    registerAdapter(LinksAdapter());
    registerAdapter(NodeAdapter());
    registerAdapter(ProtocolAdapter());
    registerAdapter(ProtocolDataAdapter());
    registerAdapter(RpcUrlAdapter());
  }
}
