// (Internal/private) Generated by the `index_generator` package with the `index_generator.yaml` configuration file.

/// Internal/private classes related to chain data repository interfaces.
library _repositories;

export 'chain_repository.dart';
export 'cosmos_chain_repository.dart';
export 'evm_chain_repository.dart';
