name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  decimal: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2

  komodo_defi_sdk: ^0.1.0
  komodo_defi_types: ^0.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  js: any

  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
