name: kdf_sdk_example
description: "An example application that demonstrates how to use the Komodo Defi SDK."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: 0.3.0
  decimal: ^3.2.1

  dragon_charts_flutter:
    path: ../../dragon_charts_flutter
  dragon_logs:
    path: ../../dragon_logs
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0-beta.4

  komodo_cex_market_data:
    path: ../../komodo_cex_market_data

  komodo_defi_rpc_methods:
    path: ../../komodo_defi_rpc_methods

  komodo_defi_sdk:
    path: ../

  komodo_defi_types:
    path: ../../komodo_defi_types

  komodo_ui:
    path: ../../komodo_ui

  logging: ^1.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
