// (Internal/private) Generated by the `index_generator` package with the `index_generator.yaml` configuration file.

/// Internal/private classes related to the assets of the Komodo DeFi Framework ecosystem.
library _assets_index;

export 'asset_extensions.dart';
export 'asset_history_storage.dart';
export 'asset_manager.dart';
export 'balance_manager.dart';
