analyzer:
  errors:
    public_member_api_docs: ignore
    invalid_annotation_target: ignore
    use_if_null_to_convert_nulls_to_bools: ignore

    
include: package:very_good_analysis/analysis_options.6.0.0.yaml