# To activate the CLI package from a local path, run:
# `dart pub global activate --source=path packages/komodo_wallet_cli`
# To upgrade the CLI package, first delete the cached package.
# The KDF version can be updated by running:
# `dart run packages/komodo_wallet_cli/bin/update_api_config.dart --branch dev --config packages/komodo_defi_framework/app_build/build_config.json --output-dir temp_downloads --source mirror --verbose`
# macOS/Linux:
# `flutter clean && rm -rf ~/.pub-cache/global_packages/komodo_wallet_cli`
# Windows:
# flutter clean && rd /s /q %USERPROFILE%\.pub-cache\global_packages\komodo_wallet_cli
# Then re-activate the package with the same as the first command.

name: komodo_wallet_cli
description: A sample command-line application with basic argument parsing.
version: 0.3.0+0
repository: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter/

environment:
  sdk: ^3.8.1

resolution: workspace

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  path: ^1.9.1
  yaml: ^3.1.3


dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.25.7

  komodo_wallet_build_transformer:
    path: ../komodo_wallet_build_transformer

assets:
  - path: assets/transformer_invoker.txt
    transformers:
        - package: komodo_wallet_build_transformer
          args: [
          # Uncomment any of the following options to disable specific build
          # steps. They are executed in the order listed in `_build_steps`
          # in `packages/komodo_wallet_build_transformer/bin/komodo_wallet_build_transformer.dart`
            # Configure fetch_defi_api in `config/build_config.yaml`
            --fetch_defi_api,
            # Configure `fetch_coin_assets` in `config/build_config.yaml`
            --fetch_coin_assets,
            --copy_platform_assets,
            # Uncomment the following option to enable concurrent build step
            # execution. This is useful for reducing build time in development,
            # but is not recommended for production builds.
            # - --concurrent,

            #! NB: There may be complications if we want to publish the
            # sub-packages as separate packages. However, Flutter's upcoming
            # support for native/web build hooks may simplify this process.
            --config_output_path=packages/komodo_wallet_cli/config/build_config.yaml
          ]

executables:
  flutter_upgrade_nested:
  update_api_config: