name: komodo_chain_data
description: Blockchain chain information models and repositories for the Komodo DeFi ecosystem.
version: 0.0.1+1
repository: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logging: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^6.0.0 # flutter.dev
  freezed: ^3.0.4
  index_generator: ^4.0.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^9.0.0