name: komodo_coins
description: "A package for fetching managing Komodo Platform coin configuration
  data storage, runtime updates, and queries."
version: 0.1.0
homepage: "komodoplatform.com"

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.2.2

  komodo_defi_types: ^0.1.0

  # meta:
  meta: ^1.15.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
