// (Internal/private) Generated by the `index_generator` package with the `index_generator.yaml` configuration file.

/// Internal/private classes related to core chain data functionality.
library _core;
