// (Internal/private) Generated by the `index_generator` package with the `index_generator.yaml` configuration file.

/// Internal/private classes related to the Trezor integration of the Komodo DeFi Framework ecosystem.
library _trezor;

export 'trezor_initialization_state.dart';
export 'trezor_manager.dart';
