name: komodo_ui
description: A high-level widget catalog relevant to building Flutter UI apps
  which consume Komodo DeFi Framework
version: 0.2.0+0
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0 <3.30.0"

dependencies:
  decimal: ^3.0.2

  flutter:
    sdk: flutter

  intl: ^0.20.2
  komodo_defi_types:
    path: ../komodo_defi_types
  mobile_scanner: ^7.0.0
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  index_generator: ^4.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^8.0.0
