name: komodo_ui
description: A high-level widget catalog relevant to building Flutter UI apps which consume Komodo DeFi Framework
version: 0.1.0+1

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
