name: komodo_ui
description: A high-level widget catalog relevant to building Flutter UI apps
  which consume Komodo DeFi Framework
version: 0.2.0+0
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0 <3.25.0"

dependencies:
  decimal: ^3.0.2

  flutter:
    sdk: flutter

  komodo_defi_types:
    path: ../komodo_defi_types
  mobile_scanner: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  index_generator: ^4.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
