// GENERATED CODE - DO NOT MODIFY BY HAND

// Generated by the `index_generator` package with the `index_generator.yaml` configuration file.

/// Utilities and helper functions to simplify the usage of the Komodo DeFi Framework RPC methods.
///
/// Note that this is for quality-of-life improvements and to reduce boilerplate code. There should
/// be no business logic in this package.
library util;

export 'methods_index_generator.dart';
