name: komodo_symbol_converter
description: A lightweight package to convert fiat/crypto prices and charts
version: 0.3.0+0
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^8.0.0
