name: komodo_symbol_converter
description: A lightweight package to convert fiat/crypto prices and charts
version: 0.1.0+1

environment:
  sdk: ^3.6.0

resolution: workspace

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
