name: komodo_mcp_server
description: MCP server exposing Komodo DeFi SDK functionality over stdio.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  meta: ^1.12.0
  uuid: ^4.5.1
  decimal: ^3.2.1
  # Monorepo-local packages
  komodo_defi_sdk:
    path: ../komodo_defi_sdk
  komodo_defi_types:
    path: ../komodo_defi_types
  komodo_defi_framework:
    path: ../komodo_defi_framework
  komodo_defi_local_auth:
    path: ../komodo_defi_local_auth
  komodo_defi_rpc_methods:
    path: ../komodo_defi_rpc_methods

executables:
  komodo_mcp_server: bin/komodo_mcp_server.dart

# No dev dependencies initially