name: Flutter package tests (matrix)

on:
  push:
    branches: [ main, develop, feat/**, fix/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  discover:
    name: Discover packages
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build package matrix from packages/*/pubspec.yaml
        id: set-matrix
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t packages < <(find packages -mindepth 1 -maxdepth 1 -type d -exec test -e '{}/pubspec.yaml' ';' -print | sort)
          if [ ${#packages[@]} -eq 0 ]; then
            echo "matrix=[]" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          json=$(printf '%s\n' "${packages[@]}" | jq -R -s -c 'split("\n")[:-1] | map({path: .})')
          echo "matrix=$json" >> "$GITHUB_OUTPUT"

  test:
    name: Flutter test (${{ matrix.package.path }})
    needs: discover
    if: ${{ needs.discover.outputs.matrix != '' && needs.discover.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.discover.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.35.1'
          architecture: x64

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            **/.dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Flutter pub get
        run: flutter pub get
        working-directory: ${{ matrix.package.path }}

      - name: Run tests
        run: flutter test -r expanded
        working-directory: ${{ matrix.package.path }}

