include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  errors:
    use_if_null_to_convert_nulls_to_bools: ignore
    omit_local_variable_types: ignore
    avoid_redundant_argument_values: ignore
