name: komodo_defi_sdk
description: A high-level opinionated library that provides a simple way to build cross-platform Komodo Defi Framework applications (primarily focused on wallets). This package seves as the entry point for the packages in this repository.
version: 0.1.0+1

# Temporarily set since published packages can't have path dependencies.
# When this package is stable, the child packages will be published to pub.dev
# and this package will depend on pub.dev hosted versions so that it can be
# published to pub.dev as well.
publish_to: 'none'

environment:
  sdk: ^3.4.0

dependencies:
  komodo_defi_framework:
    path: ../komodo_defi_framework

dev_dependencies:
  mocktail: ^1.0.4
  # test: ^1.25.7
  test: ^1.25.2
  very_good_analysis: ^6.0.0
