name: komodo_defi_sdk
description: A high-level opinionated library that provides a simple way to
  build cross-platform Komodo Defi Framework applications (primarily focused on
  wallets). This package seves as the entry point for the packages in this
  repository.
version: 0.3.0+0
repository: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

resolution: workspace

dependencies:
  collection: ^1.18.0
  decimal: ^3.2.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0-beta.4
  get_it: ^8.0.3
  http: ^1.4.0
  komodo_cex_market_data: any
  komodo_coins: any
  komodo_defi_framework: any
  komodo_defi_local_auth: any
  komodo_defi_rpc_methods: any
  komodo_defi_types: any
  komodo_ui: any

  mutex: ^3.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2

  logging: ^1.3.0
dev_dependencies:
  index_generator: ^4.0.1
  fake_async: ^1.3.3
  mocktail: ^1.0.4
  # test: ^1.25.7
  test: ^1.25.7
  very_good_analysis: ^9.0.0
# TODO: Move to a separate sub-package?
# flutter:
# assets:
#   - assets/bip-0039/english-wordlist.txt
