name: komodo_defi_sdk
description: A high-level opinionated library that provides a simple way to
  build cross-platform Komodo Defi Framework applications (primarily focused on
  wallets). This package seves as the entry point for the packages in this
  repository.
version: 0.2.1+0

# Temporarily set since published packages can't have path dependencies.
# When this package is stable, the child packages will be published to pub.dev
# and this package will depend on pub.dev hosted versions so that it can be
# published to pub.dev as well.
publish_to: "none"

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0 <3.30.0"

dependencies:
  collection: ^1.18.0
  decimal: ^3.2.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0-beta.4
  get_it: ^8.0.3
  http: ^1.3.0
  komodo_cex_market_data:
    path: ../komodo_cex_market_data
  komodo_coins:
    path: ../komodo_coins
  komodo_defi_framework:
    path: ../komodo_defi_framework
  komodo_defi_local_auth:
    path: ../komodo_defi_local_auth
  komodo_defi_rpc_methods:
    path: ../komodo_defi_rpc_methods
  komodo_defi_types:
    path: ../komodo_defi_types
  komodo_ui:
    path: ../komodo_ui

  mutex: ^3.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  index_generator: ^4.0.1
  mocktail: ^1.0.4
  # test: ^1.25.7
  test: ^1.25.2
  very_good_analysis: ^8.0.0
# TODO: Move to a separate sub-package?
# flutter:
# assets:
#   - assets/bip-0039/english-wordlist.txt
