name: komodo_defi_sdk
description: A high-level opinionated library that provides a simple way to
  build cross-platform Komodo Defi Framework applications (primarily focused on
  wallets). This package seves as the entry point for the packages in this
  repository.
version: 0.1.0+1

# Temporarily set since published packages can't have path dependencies.
# When this package is stable, the child packages will be published to pub.dev
# and this package will depend on pub.dev hosted versions so that it can be
# published to pub.dev as well.
publish_to: 'none'

environment:
  sdk: ^3.4.0
  flutter: '>=3.22.0 <3.25.0'

dependencies:

  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  
  komodo_coins:
    path: ../komodo_coins
  komodo_defi_framework:
    path: ../komodo_defi_framework
  komodo_defi_local_auth:
    path: ../komodo_defi_local_auth
  komodo_defi_rpc_methods:
    path: ../komodo_defi_rpc_methods
  komodo_defi_types:
    path: ../komodo_defi_types

  shared_preferences: ^2.3.2

dev_dependencies:
  mocktail: ^1.0.4
  # test: ^1.25.7
  test: ^1.25.2
  very_good_analysis: ^6.0.0

dependency_overrides:
  flutter_secure_storage_web:
     git:
      url: https://github.com/mogol/flutter_secure_storage.git
      ref: develop
      path: flutter_secure_storage_web

# TODO: Move to a separate sub-package?
# flutter:
  # assets:
  #   - assets/bip-0039/english-wordlist.txt
